# Generated by Django 2.2.3 on 2019-07-05 09:09

import blog.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artical',
            fields=[
                ('id', models.CharField(default=blog.utils.models.gen_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='默认标题', max_length=102)),
                ('classify', models.CharField(default='', max_length=20)),
                ('hots', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=123456789)),
                ('content', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=blog.utils.models.gen_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_name', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
                ('prefix', models.CharField(default='86', max_length=2)),
                ('web_site', models.CharField(max_length=100)),
                ('agree', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
