# Generated by Django 2.2.3 on 2019-07-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='user_id',
            field=models.CharField(max_length=36),
        ),
    ]
