# Generated by Django 2.2.3 on 2019-09-18 09:45

import blog.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artical',
            fields=[
                ('id', models.CharField(default=blog.utils.models.gen_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='默认标题', max_length=102)),
                ('classify', models.CharField(default='', max_length=20)),
                ('hots', models.IntegerField(default=0)),
                ('nices', models.IntegerField(default=0)),
                ('content', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
