# Generated by Django 2.2.3 on 2019-09-18 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_artical'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artical_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artical',
            name='user_like',
            field=models.ManyToManyField(blank=True, related_name='like_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
