# Generated by Django 2.2.3 on 2019-07-09 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artical',
            name='user_id',
        ),
        migrations.AddField(
            model_name='artical',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artical', to='blog.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatar/%Y/%m/%d'),
        ),
    ]
