# Generated by Django 2.2.3 on 2019-07-16 04:17

import blog.utils.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190709_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='nices',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(default=blog.utils.models.gen_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('word', models.TextField()),
                ('to_comment', models.CharField(default='', max_length=36)),
                ('belong_artical', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artical_comment', to='blog.Artical')),
                ('belong_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to='blog.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
