# Generated by Django 2.2.3 on 2019-07-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_artical_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='user_like',
            field=models.ManyToManyField(blank=True, related_name='like_user', to='blog.User'),
        ),
    ]
